"""empty message

Revision ID: 2c3d6c35a50f
Revises: 2a3a7cef9730
Create Date: 2021-05-08 19:37:20.953619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c3d6c35a50f'
down_revision = '2a3a7cef9730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('receiverId', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('contents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('senderId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], name='messages_receiverId_fkey'),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], name='messages_senderId_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
