"""empty message

Revision ID: 3e006fd730fb
Revises: 2c3d6c35a50f
Create Date: 2021-05-12 22:59:00.608804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e006fd730fb'
down_revision = '2c3d6c35a50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###
