"""empty message

Revision ID: b74c1227c559
Revises: e54167465f32
Create Date: 2021-04-22 15:32:57.392896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74c1227c559'
down_revision = 'e54167465f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'username_from')
    op.drop_column('invitations', 'username_to')
    op.drop_column('messages', 'username_from')
    op.drop_column('messages', 'username_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username_to', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('username_from', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('invitations', sa.Column('username_to', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('invitations', sa.Column('username_from', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
