"""empty message

Revision ID: c853798dd21e
Revises: b74c1227c559
Create Date: 2021-04-22 15:43:23.684682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c853798dd21e'
down_revision = 'b74c1227c559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['user_from_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
